application: zagwedding
version: 1
runtime: python27
api_version: 1
threadsafe: yes

skip_files:
- ^.+\.scss$
- ^node_modules.*$

libraries:
- name: jinja2
  version: "2.6"

handlers:
- url: /static
  static_dir: static

- url: /
  script: application.app